### PR TITLE
Added tests

### PR DESCRIPTION
**Pull request by tre3x**
### **PR Type**
Tests, Enhancement

___

### **Description**
- Added a new script in `test.py` to list and sort `.h5` files in the `weights` directory and print the sorted list.
- Enhanced `train.py` to dynamically load the latest weights file based on the sorted list of `.h5` files.
- Updated `n_trials` to 170000 and modified `progbar` initialization to start from the latest loaded iteration.
- Added functionality to log episode statistics (average correct count and winrate) to `logsNew.txt`.
- Included log entries in `logsNew.txt` for various episodes.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Tests
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>test.py</strong><dd><code>Added script to list and sort `.h5` files.</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

test.py
<li>Added script to list and sort <code>.h5</code> files in the <code>weights</code> directory.<br> <li> Prints sorted list of file names.<br>

</details>
    

  </td>
  <td><a href="https://github.com/tre3x/HangMan-Bot/pull/2/files#diff-3665d65394f4f58a56a256ad6dd8621c68118d90fe56a19387e251c19cec2d2e">+10/-0</a>&nbsp; &nbsp; </td>
</tr>                    
</table></td></tr><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>train.py</strong><dd><code>Dynamically load latest weights and log episode statistics.</code></dd></summary>
<hr>

train.py
<li>Added code to dynamically load the latest weights file.<br> <li> Updated <code>n_trials</code> and <code>progbar</code> initialization.<br> <li> Added logging of episode statistics to <code>logsNew.txt</code>.<br>

</details>
    

  </td>
  <td><a href="https://github.com/tre3x/HangMan-Bot/pull/2/files#diff-ed183d67207df065a11e1289f19d34cc2abbc5448dea952683cfe9728c342b95">+19/-3</a>&nbsp; &nbsp; </td>
</tr>                    
</table></td></tr><tr><td><strong>Miscellaneous
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>logsNew.txt</strong><dd><code>Added log entries for episode statistics.</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

logsNew.txt
<li>Added log entries for episodes with average correct count and winrate.<br> <br>

</details>
    

  </td>
  <td><a href="https://github.com/tre3x/HangMan-Bot/pull/2/files#diff-083386a800a2126e838554354d4bccf0ab503053d7510c50e8149509e8f7d80e">+388/-0</a>&nbsp; </td>
</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by tre3x** [comment]
Preparing PR description...

**Comment by shrn2** [comment]
**[PR Description](https://github.com/tre3x/HangMan-Bot/pull/2)** updated to latest commit (https://github.com/tre3x/HangMan-Bot/commit/9a5cdf38a6fdf66cd1aaa60e66cf8a4170e47cab)

**Comment by tre3x** [comment]
Preparing review...

**Comment by shrn2** [comment]
## PR Review 🔍

<table>
<tr>
<tr><td> ⏱️&nbsp;<strong>Estimated&nbsp;effort&nbsp;to&nbsp;review [1-5]</strong></td><td>

3, because the PR involves multiple files and functionalities including file operations, dynamic loading of model weights, and logging. The logic for sorting and parsing filenames requires careful review to ensure correctness and efficiency. Additionally, the changes in the training loop and logging mechanism need to be validated for proper execution and performance implications.


</td></tr>
<tr><td> 🧪&nbsp;<strong>Relevant tests</strong></td><td>

No


</td></tr>
<tr><td rowspan=2> ⚡&nbsp;<strong>Possible issues</strong></td>
<td>

<strong>Possible Bug:</strong> The lambda function used for sorting `file_names` assumes all filenames strictly follow a naming convention that includes an integer at the end before the `.h5` extension. This might cause errors if any filename does not follow this expected format.</td></tr>
<tr>
<td>

<strong>Efficiency Concern:</strong> The current method of opening and closing the log file within every logging operation inside the loop in `train.py` could be inefficient, especially with a large number of episodes. This might affect performance due to frequent I/O operations.</td></tr>
<tr><td> 🔒&nbsp;<strong>Security concerns</strong></td><td>

No

</td></tr>
</table>


<details><summary> <strong>Code feedback:</strong></summary>

<hr><table><tr><td>relevant file</td><td>train.py
</td></tr><tr><td>suggestion &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>

<strong>

Consider using a context manager for file operations to ensure that the file is properly closed after its suite finishes executing, even if exceptions are raised. This approach is more Pythonic and reduces the risk of file corruption or leaks. [important]

</strong>
</td></tr><tr><td>relevant line</td><td><a href='https://github.com/tre3x/HangMan-Bot/pull/2/files#diff-ed183d67207df065a11e1289f19d34cc2abbc5448dea952683cfe9728c342b95R82'>log.close()</a></td></tr></table><hr>

<table><tr><td>relevant file</td><td>train.py
</td></tr><tr><td>suggestion &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>

<strong>

To enhance the robustness of the filename sorting logic, add error handling to manage cases where the filename does not strictly follow the expected naming convention. This could prevent runtime errors that would occur from trying to convert a non-integer string to an integer. [important]

</strong>
</td></tr><tr><td>relevant line</td><td><a href='https://github.com/tre3x/HangMan-Bot/pull/2/files#diff-ed183d67207df065a11e1289f19d34cc2abbc5448dea952683cfe9728c342b95R30'>file_names = sorted(list(map(lambda x: int(x.split('.')[0].split('_')[-1]) ,file_names)))</a></td></tr></table><hr>

<table><tr><td>relevant file</td><td>train.py
</td></tr><tr><td>suggestion &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>

<strong>

Instead of repeatedly opening and closing the log file within the loop, open the file once outside the loop and write to it as needed. This change would improve performance by reducing the number of I/O operations. [important]

</strong>
</td></tr><tr><td>relevant line</td><td><a href='https://github.com/tre3x/HangMan-Bot/pull/2/files#diff-ed183d67207df065a11e1289f19d34cc2abbc5448dea952683cfe9728c342b95R80'>log = open("logsNew.txt", "a")</a></td></tr></table><hr>

<table><tr><td>relevant file</td><td>test.py
</td></tr><tr><td>suggestion &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>

<strong>

Add error handling for the directory listing operation to manage exceptions that could arise if the directory does not exist or there are permission issues. This would make the script more robust and user-friendly by providing clear error messages. [medium]

</strong>
</td></tr><tr><td>relevant line</td><td><a href='https://github.com/tre3x/HangMan-Bot/pull/2/files#diff-3665d65394f4f58a56a256ad6dd8621c68118d90fe56a19387e251c19cec2d2eR4'>for file in os.listdir("weights"):</a></td></tr></table><hr>

</details>

**Comment by tre3x** [comment]
Preparing answer...

**Comment by shrn2** [comment]
### **Ask**❓
Is there any test script in the PR?

### **Answer:**
Yes, there is a test script in the PR. The `test.py` file has been added to list and sort `.h5` files in the `weights` directory and print the sorted list. The relevant code snippet is:

```python
+import os
+
+file_names = []
+for file in os.listdir("weights"):
+    if file.endswith(".h5"):
+        file_names.append(file)
+
+
+file_names = sorted(list(map(lambda x: int(x.split('.')[0].split('_')[-1]) ,file_names)))
+print(file_names)
```

**Pull request closed without merging**
