### PR TITLE
Added tests and logs

### PR DESCRIPTION
**Pull request by shrn2**
### **PR Type**
Tests, Enhancement

___

### **Description**
- Added a script in `test.py` to list and sort `.h5` files in the `weights` directory and print the sorted list.
- Enhanced `train.py` to dynamically load the latest weights file based on sorted file names from the `weights` directory.
- Updated `n_trials` to 170000 and adjusted `progbar` initialization accordingly.
- Implemented logging of average correct count and win rate to `logsNew.txt`.
- Added log entries in `logsNew.txt` for various training episodes.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Tests
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>test.py</strong><dd><code>Add script to list and sort `.h5` files.</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

test.py
<li>Added script to list and sort <code>.h5</code> files in the <code>weights</code> directory.<br> <li> Printed sorted list of file names.<br>

</details>
    

  </td>
  <td><a href="https://github.com/tre3x/HangMan-Bot/pull/3/files#diff-3665d65394f4f58a56a256ad6dd8621c68118d90fe56a19387e251c19cec2d2e">+10/-0</a>&nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>logsNew.txt</strong><dd><code>Add log entries for training episodes.</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

logsNew.txt
<li>Added log entries for episodes with average correct count and win <br>rate.<br>

</details>
    

  </td>
  <td><a href="https://github.com/tre3x/HangMan-Bot/pull/3/files#diff-083386a800a2126e838554354d4bccf0ab503053d7510c50e8149509e8f7d80e">+388/-0</a>&nbsp; </td>
</tr>                    
</table></td></tr><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>train.py</strong><dd><code>Enhance training script with dynamic weight loading and logging.</code></dd></summary>
<hr>

train.py
<li>Added code to list and sort <code>.h5</code> files in the <code>weights</code> directory.<br> <li> Dynamically loaded the latest weights file based on sorted file names.<br> <li> Updated <code>n_trials</code> and <code>progbar</code> initialization.<br> <li> Added logging of average correct count and win rate to <code>logsNew.txt</code>.<br>

</details>
    

  </td>
  <td><a href="https://github.com/tre3x/HangMan-Bot/pull/3/files#diff-ed183d67207df065a11e1289f19d34cc2abbc5448dea952683cfe9728c342b95">+19/-3</a>&nbsp; &nbsp; </td>
</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by tre3x** [comment]
Preparing PR description...

**Comment by shrn2** [comment]
**[PR Description](https://github.com/tre3x/HangMan-Bot/pull/3)** updated to latest commit (https://github.com/tre3x/HangMan-Bot/commit/9a5cdf38a6fdf66cd1aaa60e66cf8a4170e47cab)

**Comment by tre3x** [comment]
Preparing review...

**Comment by shrn2** [comment]
## PR Review 🔍

### (Review updated until commit https://github.com/tre3x/HangMan-Bot/commit/9a5cdf38a6fdf66cd1aaa60e66cf8a4170e47cab)


<table>
<tr>
<tr><td> ⏱️&nbsp;<strong>Estimated&nbsp;effort&nbsp;to&nbsp;review [1-5]</strong></td><td>

3, because the PR involves multiple files and significant changes including file sorting, dynamic loading, logging, and updating training parameters. The logic is moderately complex, involving file operations and updates to training procedures.


</td></tr>
<tr><td> 🧪&nbsp;<strong>Relevant tests</strong></td><td>

No


</td></tr>
<tr><td rowspan=2> ⚡&nbsp;<strong>Possible issues</strong></td>
<td>

<strong>Possible Bug:</strong> The sorting of `.h5` files assumes all filenames can be converted to integers after splitting, which might not always be the case. This could lead to a ValueError if the filename format is not as expected.</td></tr>
<tr>
<td>

<strong>Performance Issue:</strong> The code opens and closes the log file multiple times within a loop, which is inefficient and can be optimized by using a context manager or opening the file once outside the loop.</td></tr>
<tr><td> 🔒&nbsp;<strong>Security concerns</strong></td><td>

No

</td></tr>
</table>


<details><summary> <strong>Code feedback:</strong></summary>

<hr><table><tr><td>relevant file</td><td>train.py
</td></tr><tr><td>suggestion &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>

<strong>

Consider using a context manager for file operations to ensure that the file is properly closed after its contents are written, even if an error occurs. This approach is more Pythonic and reduces the risk of file corruption. [important]

</strong>
</td></tr><tr><td>relevant line</td><td><a href='https://github.com/tre3x/HangMan-Bot/pull/3/files#diff-ed183d67207df065a11e1289f19d34cc2abbc5448dea952683cfe9728c342b95R82'>log.close()</a></td></tr></table><hr>

<table><tr><td>relevant file</td><td>test.py
</td></tr><tr><td>suggestion &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>

<strong>

Add error handling for the conversion of file names to integers. This will prevent the program from crashing if there are any non-integer filenames. Use a try-except block around the conversion and handle the exception appropriately. [important]

</strong>
</td></tr><tr><td>relevant line</td><td><a href='https://github.com/tre3x/HangMan-Bot/pull/3/files#diff-3665d65394f4f58a56a256ad6dd8621c68118d90fe56a19387e251c19cec2d2eR9'>file_names = sorted(list(map(lambda x: int(x.split('.')[0].split('_')[-1]) ,file_names)))</a></td></tr></table><hr>

<table><tr><td>relevant file</td><td>train.py
</td></tr><tr><td>suggestion &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>

<strong>

Instead of repeatedly opening and closing the log file in the loop, open the file once outside the loop and write to it as needed. This will improve performance by reducing the overhead of multiple file operations. [important]

</strong>
</td></tr><tr><td>relevant line</td><td><a href='https://github.com/tre3x/HangMan-Bot/pull/3/files#diff-ed183d67207df065a11e1289f19d34cc2abbc5448dea952683cfe9728c342b95R80'>log = open("logsNew.txt", "a")</a></td></tr></table><hr>

<table><tr><td>relevant file</td><td>train.py
</td></tr><tr><td>suggestion &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>

<strong>

To ensure that the dynamically loaded weight file exists and avoid runtime errors, add a check to confirm that `file_names` is not empty before attempting to access its last element. This prevents an IndexError if no `.h5` files are found. [important]

</strong>
</td></tr><tr><td>relevant line</td><td><a href='https://github.com/tre3x/HangMan-Bot/pull/3/files#diff-ed183d67207df065a11e1289f19d34cc2abbc5448dea952683cfe9728c342b95R32'>LOAD_ITERATION = file_names[-1]</a></td></tr></table><hr>

</details>

**Comment by tre3x** [comment]
Preparing answer...

**Comment by shrn2** [comment]
### **Ask**❓
what does the test script doin the PR?

### **Answer:**
The test script `test.py` introduced in the PR performs the following actions:

1. **Imports the `os` module**: This module is used to interact with the operating system, particularly for file and directory operations.

2. **Initializes an empty list `file_names`**: This list will store the names of files that meet certain criteria.

3. **Lists and filters files in the `weights` directory**:
   - It iterates over all files in the `weights` directory.
   - It checks if each file ends with the `.h5` extension (which is typically used for HDF5 files, often used to store neural network weights).
   - If a file meets this criterion, its name is appended to the `file_names` list.

4. **Sorts the filtered file names**:
   - The script maps each file name to an integer extracted from the file name. Specifically, it splits the file name by underscores and periods to extract the numeric part.
   - It sorts the list of these integers in ascending order.

5. **Prints the sorted list**: Finally, the script prints the sorted list of integers, which represent the sorted order of the `.h5` files based on the numeric part of their names.

Here is the relevant code from `test.py`:

```python
import os

file_names = []
for file in os.listdir("weights"):
    if file.endswith(".h5"):
        file_names.append(file)

file_names = sorted(list(map(lambda x: int(x.split('.')[0].split('_')[-1]), file_names)))
print(file_names)
```

This script is useful for verifying that the `.h5` files in the `weights` directory are correctly listed and sorted, which can be important for loading the latest model weights in other parts of the application.

**Comment by tre3x** [comment]
Preparing PR description...

**Comment by shrn2** [comment]
**[PR Description](https://github.com/tre3x/HangMan-Bot/pull/3)** updated to latest commit (https://github.com/tre3x/HangMan-Bot/commit/9a5cdf38a6fdf66cd1aaa60e66cf8a4170e47cab)

**Comment by tre3x** [comment]
Preparing PR description...

**Comment by shrn2** [comment]
**[PR Description](https://github.com/tre3x/HangMan-Bot/pull/3)** updated to latest commit (https://github.com/tre3x/HangMan-Bot/commit/9a5cdf38a6fdf66cd1aaa60e66cf8a4170e47cab)

**Comment by tre3x** [comment]
Preparing PR description...

**Comment by shrn2** [comment]
**[PR Description](https://github.com/tre3x/HangMan-Bot/pull/3)** updated to latest commit (https://github.com/tre3x/HangMan-Bot/commit/9a5cdf38a6fdf66cd1aaa60e66cf8a4170e47cab)

**Comment by shrn2** [comment]
Preparing PR description...

**Comment by tre3x** [comment]
Preparing PR description...

**Comment by shrn2** [comment]
**[PR Description](https://github.com/tre3x/HangMan-Bot/pull/3)** updated to latest commit (https://github.com/tre3x/HangMan-Bot/commit/9a5cdf38a6fdf66cd1aaa60e66cf8a4170e47cab)

**Comment by tre3x** [comment]
Preparing review...

**Comment by shrn2** [comment]
**[Persistent review](https://github.com/tre3x/HangMan-Bot/pull/3#issuecomment-2127621907)** updated to latest commit https://github.com/tre3x/HangMan-Bot/commit/9a5cdf38a6fdf66cd1aaa60e66cf8a4170e47cab

**Comment by shrn2** [comment]
Preparing PR description...

**Comment by shrn2** [comment]
Preparing PR description...

**Comment by shrn2** [comment]
Preparing PR description...

**Comment by tre3x** [comment]
Preparing PR description...

**Comment by shrn2** [comment]
**[PR Description](https://github.com/tre3x/HangMan-Bot/pull/3)** updated to latest commit (https://github.com/tre3x/HangMan-Bot/commit/9a5cdf38a6fdf66cd1aaa60e66cf8a4170e47cab)

**Comment by tre3x** [comment]
Preparing PR description...

**Comment by shrn2** [comment]
**[PR Description](https://github.com/tre3x/HangMan-Bot/pull/3)** updated to latest commit (https://github.com/tre3x/HangMan-Bot/commit/9a5cdf38a6fdf66cd1aaa60e66cf8a4170e47cab)

**Comment by shrn2** [comment]
Preparing PR description...

**Comment by tre3x** [comment]
Preparing review...

**Comment by shrn2** [comment]
**[Persistent review](https://github.com/tre3x/HangMan-Bot/pull/3#issuecomment-2127621907)** updated to latest commit https://github.com/tre3x/HangMan-Bot/commit/9a5cdf38a6fdf66cd1aaa60e66cf8a4170e47cab

**Comment by shrn2** [comment]
Preparing review...

**Comment by shrn2** [comment]
Preparing PR description...

**Comment by shrn2** [comment]
Preparing PR description...

**Comment by shrn2** [comment]
Preparing PR description...

**Comment by shrn2** [comment]
Preparing PR description...

**Comment by shrn2** [comment]
Preparing PR description...

**Comment by shrn2** [comment]
Preparing PR description...

**Comment by shrn2** [comment]
Preparing PR description...

**Comment by shrn2** [comment]
Preparing PR description...

**Comment by shrn2** [comment]
Preparing PR description...

**Comment by shrn2** [comment]
Preparing PR description...

**Comment by shrn2** [comment]
Preparing PR description...

**Comment by shrn2** [comment]
Preparing PR description...

**Comment by shrn2** [comment]
Preparing PR description...

**Comment by shrn2** [comment]
Preparing PR description...

**Comment by shrn2** [comment]
Preparing PR description...

**Comment by shrn2** [comment]
Preparing PR description...

**Comment by shrn2** [comment]
Preparing PR description...

**Comment by shrn2** [comment]
Preparing PR description...

**Comment by shrn2** [comment]
Preparing PR description...

**Comment by shrn2** [comment]
Preparing PR description...

**Comment by shrn2** [comment]
Preparing PR description...

**Comment by shrn2** [comment]
Preparing PR description...

**Comment by shrn2** [comment]
Preparing PR description...

**Comment by shrn2** [comment]
Preparing PR description...

**Comment by tre3x** [comment]
Preparing answer...

**Comment by shrn2** [comment]
### **Ask**❓
What is the PR about?

### **Answer:**
The PR titled 'Added tests and logs' is about making several enhancements and additions to the `HangMan-Bot` project. Specifically, it includes:

1. **Tests:**
   - A script added to `test.py` to list and sort `.h5` files in the `weights` directory and print the sorted list.

2. **Enhancements:**
   - Modifications to `train.py` to dynamically load the latest weights file based on sorted file names from the `weights` directory.
   - Updating the number of trials (`n_trials`) to 170000 and adjusting the `progbar` initialization accordingly.
   - Implementing logging of average correct count and win rate to a new file `logsNew.txt`.
   - Adding log entries in `logsNew.txt` for various training episodes.

These changes aim to improve the testing and logging mechanisms of the project, making it more dynamic and informative.

**Comment by shrn2** [comment]
### **Ask**❓
What is the PR about?

### **Answer:**
The PR is about adding tests and enhancing the functionality of the Hangman Bot project. Specifically, it introduces the following changes:

1. **Tests**:
   - A script in `test.py` to list and sort `.h5` files in the `weights` directory and print the sorted list.

2. **Enhancements**:
   - In `train.py`, the code is enhanced to dynamically load the latest weights file based on sorted file names from the `weights` directory.
   - The number of trials (`n_trials`) is updated to 170000.
   - The progress bar (`progbar`) initialization is adjusted to start from the latest iteration.
   - Logging of average correct count and win rate to `logsNew.txt` is implemented.
   - Log entries for various training episodes are added to `logsNew.txt`.

These changes aim to improve the testing process, make the training process more dynamic, and enhance logging for better tracking of training progress.

**Comment by shrn2** [comment]
### **Ask**❓
What is the PR about?

### **Answer:**
The PR is about adding tests and enhancing the existing functionality of a Hangman bot project. Specifically, it includes the following changes:

1. **Tests**:
   - A script is added in `test.py` to list and sort `.h5` files in the `weights` directory and print the sorted list.

2. **Enhancements**:
   - In `train.py`, the code is enhanced to dynamically load the latest weights file based on sorted file names from the `weights` directory.
   - The number of trials (`n_trials`) is updated to 170000, and the progress bar (`progbar`) initialization is adjusted accordingly.
   - Logging of average correct count and win rate to `logsNew.txt` is implemented.
   - Log entries for various training episodes are added to `logsNew.txt`.

These changes aim to improve the testing, training, and logging mechanisms of the Hangman bot project.

**Comment by shrn2** [comment]
### **Ask**❓
What is the PR about?

### **Answer:**
The PR is about adding tests and enhancing the existing codebase for a Hangman bot. Specifically, it introduces the following changes:

1. **Tests**:
   - A script in `test.py` to list and sort `.h5` files in the `weights` directory and print the sorted list.

2. **Enhancements**:
   - In `train.py`, the code is enhanced to dynamically load the latest weights file based on sorted file names from the `weights` directory.
   - The number of trials (`n_trials`) is updated to 170000, and the progress bar (`progbar`) initialization is adjusted accordingly.
   - Logging of average correct count and win rate to `logsNew.txt` is implemented.
   - Log entries for various training episodes are added to `logsNew.txt`.

These changes aim to improve the testing process, make the training process more dynamic, and enhance logging for better tracking of training progress.

**Pull request closed without merging**
