### PR TITLE
Added tests

### PR DESCRIPTION
**Pull request by tre3x**
### **User description**
Test for the Hangman Bot added -- with some training technique diff.

___

### **PR Type**
Enhancement, Tests

___

### **Description**
- Added a new script (`test.py`) to list and sort `.h5` files in the `weights` directory.
- Enhanced `train.py` to dynamically load the latest weight file and log episode statistics.
- Increased the number of trials in `train.py` from 100,000 to 170,000.
- Added a new log file (`logsNew.txt`) to store episode statistics.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>test.py</strong><dd><code>Add script to list and sort weight files</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

test.py
<li>Added script to list and sort <code>.h5</code> files in the <code>weights</code> directory.<br> <li> Prints sorted list of file names.<br>

</details>
    

  </td>
  <td><a href="https://github.com/tre3x/HangMan-Bot/pull/1/files#diff-3665d65394f4f58a56a256ad6dd8621c68118d90fe56a19387e251c19cec2d2e">+10/-0</a>&nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>train.py</strong><dd><code>Enhance training script with dynamic weight loading and logging</code></dd></summary>
<hr>

train.py
<li>Added code to dynamically load the latest weight file.<br> <li> Updated training loop to use the latest weight file.<br> <li> Increased the number of trials.<br> <li> Added logging of episode statistics to a new log file.<br>

</details>
    

  </td>
  <td><a href="https://github.com/tre3x/HangMan-Bot/pull/1/files#diff-ed183d67207df065a11e1289f19d34cc2abbc5448dea952683cfe9728c342b95">+19/-3</a>&nbsp; &nbsp; </td>
</tr>                    
</table></td></tr><tr><td><strong>Miscellaneous
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>logsNew.txt</strong><dd><code>Add log file for episode statistics</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

logsNew.txt
- Added new log file to store episode statistics.

</details>
    

  </td>
  <td><a href="https://github.com/tre3x/HangMan-Bot/pull/1/files#diff-083386a800a2126e838554354d4bccf0ab503053d7510c50e8149509e8f7d80e">+388/-0</a>&nbsp; </td>
</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by shrn2** [comment]
**[PR Description](https://github.com/tre3x/HangMan-Bot/pull/1)** updated to latest commit (https://github.com/tre3x/HangMan-Bot/commit/9a5cdf38a6fdf66cd1aaa60e66cf8a4170e47cab)

**Comment by tre3x** [comment]
Preparing review...

**Comment by shrn2** [comment]
## PR Review 🔍

<table>
<tr>
<tr><td> ⏱️&nbsp;<strong>Estimated&nbsp;effort&nbsp;to&nbsp;review [1-5]</strong></td><td>

3, because the PR involves multiple files with significant changes including dynamic loading of weights, logging enhancements, and a new script for listing and sorting files. The logic changes are moderate and require careful review to ensure they function as intended without introducing bugs.


</td></tr>
<tr><td> 🧪&nbsp;<strong>Relevant tests</strong></td><td>

No


</td></tr>
<tr><td rowspan=2> ⚡&nbsp;<strong>Possible issues</strong></td>
<td>

<strong>Possible Bug:</strong> The sorting of weight files in both `test.py` and `train.py` assumes that the file names can be directly converted to integers after splitting, which might not always be the case if the file naming convention changes or includes non-numeric characters.</td></tr>
<tr>
<td>

<strong>Performance Concern:</strong> Opening and closing the log file in `train.py` within a loop could lead to performance issues. It would be more efficient to open the file once, write all logs, and then close it after exiting the loop.</td></tr>
<tr><td> 🔒&nbsp;<strong>Security concerns</strong></td><td>

No

</td></tr>
</table>


<details><summary> <strong>Code feedback:</strong></summary>

<hr><table><tr><td>relevant file</td><td>train.py
</td></tr><tr><td>suggestion &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>

<strong>

Consider using a context manager for file operations to ensure that the file is properly closed even if an error occurs during the write operation. This approach also improves code readability and efficiency by handling file open/close automatically. [important]

</strong>
</td></tr><tr><td>relevant line</td><td><a href='https://github.com/tre3x/HangMan-Bot/pull/1/files#diff-ed183d67207df065a11e1289f19d34cc2abbc5448dea952683cfe9728c342b95R80'>log = open("logsNew.txt", "a")</a></td></tr></table><hr>

<table><tr><td>relevant file</td><td>train.py
</td></tr><tr><td>suggestion &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>

<strong>

To enhance the robustness of the dynamic weight loading, add error handling to manage cases where no `.h5` files are found or the list is empty, which would currently cause an IndexError. [important]

</strong>
</td></tr><tr><td>relevant line</td><td><a href='https://github.com/tre3x/HangMan-Bot/pull/1/files#diff-ed183d67207df065a11e1289f19d34cc2abbc5448dea952683cfe9728c342b95R32'>LOAD_ITERATION = file_names[-1]</a></td></tr></table><hr>

<table><tr><td>relevant file</td><td>test.py
</td></tr><tr><td>suggestion &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>

<strong>

Add error handling or checks to ensure that the directory exists and is accessible before attempting to list its contents. This prevents the script from crashing due to unhandled exceptions if the directory is missing or permissions are incorrect. [important]

</strong>
</td></tr><tr><td>relevant line</td><td><a href='https://github.com/tre3x/HangMan-Bot/pull/1/files#diff-3665d65394f4f58a56a256ad6dd8621c68118d90fe56a19387e251c19cec2d2eR4'>for file in os.listdir("weights"):</a></td></tr></table><hr>

<table><tr><td>relevant file</td><td>train.py
</td></tr><tr><td>suggestion &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>

<strong>

Instead of manually managing file opening and closing, use `with open(...) as log:` for handling log file operations. This ensures that the file is always closed properly, even if an error occurs during file operations. [important]

</strong>
</td></tr><tr><td>relevant line</td><td><a href='https://github.com/tre3x/HangMan-Bot/pull/1/files#diff-ed183d67207df065a11e1289f19d34cc2abbc5448dea952683cfe9728c342b95R80'>log = open("logsNew.txt", "a")</a></td></tr></table><hr>

</details>

**Comment by tre3x** [comment]
Preparing answer...

**Comment by shrn2** [comment]
### **Ask**❓
is there any testing script with this PR?

### **Answer:**
Yes, this PR includes a new testing script named `test.py`. The script is designed to list and sort `.h5` files in the `weights` directory and print the sorted list of file names. Here is the relevant code from `test.py`:

```python
import os

file_names = []
for file in os.listdir("weights"):
    if file.endswith(".h5"):
        file_names.append(file)

file_names = sorted(list(map(lambda x: int(x.split('.')[0].split('_')[-1]), file_names)))
print(file_names)
```

**Comment by shrn2** [comment]
## PR Code Suggestions ✨

<table><thead><tr><td>Category</td><td align=left>Suggestion&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </td><td align=center>Score</td></tr><tbody><tr><td rowspan=1><strong>Best practice</strong></td>
<td>



<details><summary>Ensure proper file handling by using context managers</summary>

___


**Use context management for file operations to ensure that files are properly closed after <br>their contents are written, improving resource management.**
    
[train.py [80-82]](https://github.com/tre3x/HangMan-Bot/pull/1/files#diff-ed183d67207df065a11e1289f19d34cc2abbc5448dea952683cfe9728c342b95R80-R82)

```diff
-log = open("logsNew.txt", "a")
-log.write('Episode {} -------- Average Correct Count : {:.3f}     Last {} winrate : {:.3f}\n'.format(*views))
-log.close()
+with open("logsNew.txt", "a") as log:
+    log.write('Episode {} -------- Average Correct Count : {:.3f}     Last {} winrate : {:.3f}\n'.format(*views))
 
```
                   


<details><summary><b>Suggestion importance[1-10]: 10</b></summary>

Why: Using context management for file operations is a best practice that ensures files are properly closed, preventing potential resource leaks. This suggestion directly improves the new logging functionality introduced in the PR.


</details></details></td><td align=center>10

</td></tr><tr><td rowspan=2><strong>Enhancement</strong></td>
<td>



<details><summary>Improve the robustness and clarity of filename sorting</summary>

___


**Replace the manual parsing and sorting of filenames with a more robust method using <br>regular expressions to ensure that filenames are correctly parsed and sorted based on <br>numerical values.**
    
[test.py [9]](https://github.com/tre3x/HangMan-Bot/pull/1/files#diff-3665d65394f4f58a56a256ad6dd8621c68118d90fe56a19387e251c19cec2d2eR9-R9)

```diff
-file_names = sorted(list(map(lambda x: int(x.split('.')[0].split('_')[-1]) ,file_names)))
+import re
+file_names = sorted(file_names, key=lambda x: int(re.search(r'\d+', x).group()))
 
```
                   


<details><summary><b>Suggestion importance[1-10]: 9</b></summary>

Why: The suggestion improves the robustness and clarity of the filename sorting by using regular expressions, which is less error-prone and more readable than the manual parsing method. This change addresses a significant aspect of the new code introduced in the PR.


</details></details></td><td align=center>9

</td></tr><tr><td>



<details><summary>Simplify file filtering and appending using list comprehension</summary>

___


**Replace the manual iteration and file listing with a more concise and efficient list <br>comprehension that directly filters and appends files.**
    
[train.py [24-27]](https://github.com/tre3x/HangMan-Bot/pull/1/files#diff-ed183d67207df065a11e1289f19d34cc2abbc5448dea952683cfe9728c342b95R24-R27)

```diff
-file_names = []
-for file in os.listdir("weights"):
-    if file.endswith(".h5"):
-        file_names.append(file)
+file_names = [file for file in os.listdir("weights") if file.endswith(".h5")]
 
```
                   


<details><summary><b>Suggestion importance[1-10]: 8</b></summary>

Why: The suggestion simplifies the code by using list comprehension, making it more concise and readable. This change enhances the new code introduced in the PR for listing and filtering files.


</details></details></td><td align=center>8

</td></tr></tr></tbody></table>

**Pull request closed without merging**
